"""
Twitter OAuth 2.0 provider with unified sync/async support and PKCE.
"""

import base64
from typing import Optional, Any
from .base import BaseProvider
from src.http import HTTPClient, AsyncHTTPClient


class TwitterProviderMixin:
    """
    Mixin class containing Twitter-specific payload preparation methods.

    Requires the following attributes from implementing class:
        - client_id: str
        - client_secret: str
        - redirect_uri: str
    """

    client_id: str
    client_secret: str
    redirect_uri: str

    def _build_basic_auth_header(self) -> dict[str, str]:
        """
        Build Basic Authorization header for Twitter API.

        Returns:
            dict: Headers with Basic Authorization
        """
        auth_header = base64.b64encode(
            f"{self.client_id}:{self.client_secret}".encode()
        ).decode()

        return {
            "Content-Type": "application/x-www-form-urlencoded",
            "Authorization": f"Basic {auth_header}",
        }

    def _build_token_exchange_payload(
        self, code: str, code_verifier: str
    ) -> dict[str, str]:
        """
        Build payload for exchanging authorization code for access token with PKCE.

        Args:
            code: Authorization code from OAuth callback
            code_verifier: PKCE code verifier

        Returns:
            dict: Payload for token exchange request
        """
        return {
            "code": code,
            "grant_type": "authorization_code",
            "client_id": self.client_id,
            "redirect_uri": self.redirect_uri,
            "code_verifier": code_verifier,
        }

    def _build_revoke_payload(self, token: str) -> dict[str, str]:
        """
        Build payload for token revocation.

        Args:
            token: Token to revoke (access token)

        Returns:
            dict: Payload for revocation request
        """
        return {
            "token": token,
            "token_type_hint": "access_token",
        }


class TwitterProvider(TwitterProviderMixin, BaseProvider):
    """
    Twitter OAuth 2.0 provider with both sync and async methods.

    Note: Twitter requires PKCE (Proof Key for Code Exchange) for all OAuth 2.0 flows.
    The code verifier and challenge must be generated by the caller and managed externally.
    """

    SUPPORTS_REFRESH = False
    SUPPORTS_REVOCATION = True
    SUPPORTS_PKCE = True

    def __init__(
        self,
        client_id: str,
        client_secret: str,
        redirect_uri: str,
        scopes: Optional[list[str]] = None,
        http_client: Optional[HTTPClient] = None,
        async_http_client: Optional[AsyncHTTPClient] = None,
    ):
        """
        Initialize Twitter OAuth provider.

        Args:
            client_id: Twitter OAuth client ID
            client_secret: Twitter OAuth client secret
            redirect_uri: Registered redirect URI
            scopes: OAuth scopes (defaults to tweet.read, users.read, follows.read, follows.write)
            http_client: Custom sync HTTP client (optional)
            async_http_client: Custom async HTTP client (optional)
        """
        super().__init__(
            client_id=client_id,
            client_secret=client_secret,
            redirect_uri=redirect_uri,
            scopes=scopes,
            http_client=http_client,
            async_http_client=async_http_client,
        )

        self.authorization_endpoint = "https://twitter.com/i/oauth2/authorize"
        self.token_endpoint = "https://api.twitter.com/2/oauth2/token"
        self.revocation_endpoint = "https://api.twitter.com/2/oauth2/revoke"
        self.code_challenge_method = "S256"

    def _get_default_scopes(self) -> list[str]:
        """Get Twitter's default scopes."""
        return ["tweet.read", "users.read", "follows.read", "follows.write"]

    def exchange_code_for_access_token(
        self, code: str, code_verifier: str
    ) -> dict[str, Any]:
        """
        Exchange authorization code for access token with PKCE (SYNC).

        Args:
            code: Authorization code from Twitter
            code_verifier: PKCE code verifier used to generate code_challenge

        Returns:
            dict: Token response with access_token, token_type, etc.
        """
        headers = self._build_basic_auth_header()
        data = self._build_token_exchange_payload(code, code_verifier)

        return self._make_request(
            method="POST",
            url=self._ensure(self.token_endpoint),
            headers=headers,
            data=data,
            error_message="Failed to exchange code for access token",
        )

    def revoke_token(self, token: str) -> dict[str, Any]:
        """
        Revoke an access token (SYNC).

        Args:
            token: Token to revoke

        Returns:
            dict: Revocation response
        """
        headers = self._build_basic_auth_header()
        data = self._build_revoke_payload(token)

        result = self._make_request(
            method="POST",
            url=self._ensure(self.revocation_endpoint),
            headers=headers,
            data=data,
            error_message="Unable to revoke token",
        )

        return {"success": True, **result}

    async def aexchange_code_for_access_token(
        self, code: str, code_verifier: str
    ) -> dict[str, Any]:
        """
        Exchange authorization code for access token with PKCE (ASYNC).

        Args:
            code: Authorization code from Twitter
            code_verifier: PKCE code verifier used to generate code_challenge

        Returns:
            dict: Token response with access_token, token_type, etc.
        """
        headers = self._build_basic_auth_header()
        data = self._build_token_exchange_payload(code, code_verifier)

        return await self._amake_request(
            method="POST",
            url=self._ensure(self.token_endpoint),
            headers=headers,
            data=data,
            error_message="Failed to exchange code for access token",
        )

    async def arevoke_token(self, token: str) -> dict[str, Any]:
        """
        Revoke an access token (ASYNC).

        Args:
            token: Token to revoke

        Returns:
            dict: Revocation response
        """
        headers = self._build_basic_auth_header()
        data = self._build_revoke_payload(token)

        result = await self._amake_request(
            method="POST",
            url=self._ensure(self.revocation_endpoint),
            headers=headers,
            data=data,
            error_message="Unable to revoke token",
        )

        return {"success": True, **result}
